

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

spring.data.mongodb.database=bookclub
spring.data.mongodb.uri=mongodb+srv://bookclub_user:Bookclub2026@bellevueuniversity.t2iiezr.mongodb.net/bookclub?retryWrites=true&w=majority&appName=BellevueUniversity
