

spring.data.mongodb.database=bookclub
spring.mongodb.uri=mongodb+srv://bookclub_user:Bookclub2026@bellevueuniversity.t2iiezr.mongodb.net/bookclub?retryWrites=true&w=majority&appName=BellevueUniversity





